### ISSUE TITLE
Unknown transform "name/cti/kebab"

### ISSUE THREAD

**Issue by traed** [nado1001/style-dictionary-tailwindcss-transformer#368]
Trying to use the basic example to generate a tailwind config. I have no idea what this means 🙃

Error: 
Unknown transform "name/cti/kebab" found in platform "tailwind":
"name/cti/kebab" does not match the name of a registered transform.

    at transformConfig (file:///Users/mattias/Code/c2-tokens-test/node_modules/.pnpm/style-dictionary@4.0.1/node_modules/style-dictionary/lib/transform/config.js:95:11)
    at StyleDictionary.getPlatform (file:///Users/mattias/Code/c2-tokens-test/node_modules/.pnpm/style-dictionary@4.0.1/node_modules/style-dictionary/lib/StyleDictionary.js:561:28)
    at async StyleDictionary.buildPlatform (file:///Users/mattias/Code/c2-tokens-test/node_modules/.pnpm/style-dictionary@4.0.1/node_modules/style-dictionary/lib/StyleDictionary.js:840:44)
    at async Promise.all (index 0)
    at async StyleDictionary.buildAllPlatforms (file:///Users/mattias/Code/c2-tokens-test/node_modules/.pnpm/style-dictionary@4.0.1/node_modules/style-dictionary/lib/StyleDictionary.js:885:7)

Node.js v20.15.0
 ELIFECYCLE  Command failed with exit code 1.

**Comment by JustDoItSascha** [comment]
I have exactly the same issue right now

**Comment by JustDoItSascha** [comment]
@traed Found the issue: You have to use Style Dictionary v3, not v4!

**Comment by traed** [comment]
Thanks. I found that too, but sadly this whole ecosystem seem to have more issues than is fixable. This plugin only seem to support the legacy (non-W3C) format of design tokens. The exported design tokens I have don't follow any standard either and every implementation seem to do their own thing. I ended up writing my own parser that doesn't use style dictionary at all.
